default: &default
  adapter: mysql2
  encoding: utf8
  database: react_rails_sample
  pool: 5
  username: rails
  password: hoge
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  database: react_rails_sample
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock